site_name: ebpf Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - eBPF overview: ebpf.md
    - An implement in zCore: zcore.md
    - migrate to rCore tutorial: rcore.md

theme: readthedocs