site_name: ebpf Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - eBPF overview: ebpf.md
    - source level document: doc.md
    - rCore tutoria migration: rcore.md
    - zCore reproduce guide: zcore.md

theme: readthedocs