site_name: ebpf Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - eBPF overview: ebpf.md
    - zCore implementation: zcore.md
    - rCore tutoria migration: rcore.md

theme: readthedocs